import fs from "node:fs/promises";
import path from "node:path";

const GENERATED = "<!-- Generated by infra-starter-pack. Safe to regenerate. -->";

function titleCase(value) {
  return value.replace(/^@[^/]+\//, "").replace(/[-_]+/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

function mdList(values, empty = "None detected") {
  return values.length ? values.map((value) => `- ${value}`).join("\n") : `- ${empty}`;
}

function routeTable(routes) {
  if (!routes.length) return "No HTTP routes were detected heuristically. Add an OpenAPI 3.x file for authoritative endpoint documentation.";
  return [
    "| Method | Path | Source | Evidence |",
    "| --- | --- | --- | --- |",
    ...routes.map((route) => `| \`${route.method}\` | \`${route.path}\` | \`${route.source}\` | ${route.confidence} |`)
  ].join("\n");
}

async function writeGenerated(file, contents, force) {
  const existing = await fs.readFile(file, "utf8").catch(() => null);
  if (existing !== null && !force && !existing.includes(GENERATED)) {
    throw new Error(`Refusing to overwrite user-owned file: ${file}. Re-run with --force if intentional.`);
  }
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, contents, "utf8");
}

function docsConfig(report) {
  const groups = [
    { group: "Get started", pages: ["docs/index", "docs/architecture", "docs/api-overview", "docs/quality"] }
  ];
  for (const spec of report.openapi) groups.push({ group: spec.title || "API reference", openapi: spec.path });
  return {
    $schema: "https://mintlify.com/docs.json",
    theme: "mint",
    name: `${titleCase(report.name)} Docs`,
    colors: { primary: "#2563EB", light: "#60A5FA", dark: "#1D4ED8" },
    navigation: { groups }
  };
}

function workflow() {
  return `# Generated by infra-starter-pack. Safe to regenerate.
name: Infra starter checks

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  mintlify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npx --yes mint@latest validate

  replay-qa:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Launch Replay QA and wait for findings
        env:
          REPLAY_QA_TOKEN: \${{ secrets.REPLAY_QA_TOKEN }}
          REPLAY_QA_TARGET_URL: \${{ vars.REPLAY_QA_TARGET_URL }}
        run: npx --yes infra-starter-pack@latest replay --target-url "$REPLAY_QA_TARGET_URL" --wait --report infra-reports/replay-qa.json
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: replay-qa-report
          path: infra-reports/replay-qa.json
`;
}

export async function generateStarter(report, { root = report.root, force = false } = {}) {
  const name = titleCase(report.name);
  const languageLines = report.languages.map((item) => `${item.name} (${item.files} files)`);
  const frameworkLines = report.frameworks;
  const files = new Map([
    ["docs.json", `${JSON.stringify(docsConfig(report), null, 2)}\n`],
    ["docs/index.mdx", `${GENERATED}\n---\ntitle: \"${name}\"\ndescription: \"Repository-aware documentation generated by infra-starter-pack\"\n---\n\n# ${name}\n\n${report.description || "Welcome to the project documentation."}\n\n## What was detected\n\n${mdList(languageLines)}\n\n## Frameworks\n\n${mdList(frameworkLines)}\n\n<Info>This page is generated from repository evidence. Review product claims and examples before publishing.</Info>\n`],
    ["docs/architecture.mdx", `${GENERATED}\n---\ntitle: \"Architecture\"\ndescription: \"A generated inventory of the repository\"\n---\n\n# Architecture\n\n| Signal | Detected value |\n| --- | --- |\n| Package manager | ${report.packageManager || "Not detected"} |\n| Files scanned | ${report.totals.files} |\n| Source files | ${report.totals.sourceFiles} |\n| Frameworks | ${report.frameworks.join(", ") || "Not detected"} |\n| OpenAPI specs | ${report.openapi.length} |\n\n## Useful commands\n\n${Object.keys(report.scripts).length ? Object.keys(report.scripts).map((script) => `- \`${report.packageManager || "npm"} run ${script}\``).join("\n") : "- No package scripts detected"}\n`],
    ["docs/api-overview.mdx", `${GENERATED}\n---\ntitle: \"API overview\"\ndescription: \"OpenAPI sources and heuristically detected routes\"\n---\n\n# API overview\n\n## OpenAPI sources\n\n${report.openapi.length ? report.openapi.map((spec) => `- \`${spec.path}\` — ${spec.title}, OpenAPI ${spec.version}, ${spec.endpointCount} paths`).join("\n") : "No OpenAPI document was found. Add an OpenAPI 3.0 or 3.1 JSON/YAML file and regenerate to get Mintlify's interactive API reference."}\n\n## Detected routes\n\n${routeTable(report.routes)}\n\n<Warning>Route detection is a convenience inventory, not an API contract. OpenAPI is the authoritative input for generated API reference pages.</Warning>\n`],
    ["docs/quality.mdx", `${GENERATED}\n---\ntitle: \"Runtime quality with Replay\"\ndescription: \"How this project uses Replay QA\"\n---\n\n# Runtime quality with Replay QA\n\nReplay QA tests a running web application, not source code in isolation. It explores user journeys, writes and executes browser tests, records runtime behavior, and returns root-cause reports for bugs it finds.\n\n## Run a scan\n\n\`\`\`bash\nexport REPLAY_QA_TOKEN=\"lqa_...\"\nnpx infra-starter-pack replay \\\n  --target-url \"https://your-preview.example.com\" \\\n  --wait \\\n  --report infra-reports/replay-qa.json\n\`\`\`\n\nFor localhost, add \`--reverse-proxy\`, then follow the returned Replay proxy setup URL. Never commit the token or test credentials.\n\n## GitHub-native option\n\nInstall the Replay QA GitHub App from a Replay QA project to test pushes and pull requests without a workflow file. Publish source maps for file-and-line root cause reports.\n`],
    ["docs/infra-starter-scan.json", `${JSON.stringify({ ...report, root: "." }, null, 2)}\n`],
    [".github/workflows/infra-starter.yml", workflow()]
  ]);

  for (const [relative, contents] of files) {
    await writeGenerated(path.join(root, relative), contents, force);
  }
  return [...files.keys()];
}
