import fs from "node:fs/promises";
import path from "node:path";
import { createHash } from "node:crypto";

const GENERATED = "{/* Generated by infra-starter-pack. Safe to regenerate. */}";
const MANIFEST_PATH = ".infra-starter/manifest.json";

function titleCase(value) {
  return value.replace(/^@[^/]+\//, "").replace(/[-_]+/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

function mdList(values, empty = "None detected") {
  return values.length ? values.map((value) => `- ${value}`).join("\n") : `- ${empty}`;
}

function routeTable(routes) {
  if (!routes.length) return "No HTTP routes were detected heuristically. Add an OpenAPI 3.x file for authoritative endpoint documentation.";
  return [
    "| Method | Path | Source | Evidence |",
    "| --- | --- | --- | --- |",
    ...routes.map((route) => `| \`${route.method}\` | \`${route.path}\` | \`${route.source}\` | ${route.confidence} |`)
  ].join("\n");
}

function hash(contents) {
  return createHash("sha256").update(contents).digest("hex");
}

async function readManifest(root) {
  try {
    const manifest = JSON.parse(await fs.readFile(path.join(root, MANIFEST_PATH), "utf8"));
    return manifest?.schemaVersion === 1 && manifest?.files ? manifest : null;
  } catch {
    return null;
  }
}

async function assertSafeToWrite(root, relative, contents, force, manifest) {
  if (force) return;
  const file = path.join(root, relative);
  const existing = await fs.readFile(file, "utf8").catch(() => null);
  if (existing === null || existing === contents || existing.includes(GENERATED)) return;
  const previousHash = manifest?.files?.[relative];
  if (previousHash && hash(existing) === previousHash) return;
  throw new Error(`Refusing to overwrite user-owned or modified file: ${file}. Re-run with --force if intentional.`);
}

function docsConfig(report) {
  const groups = [
    { group: "Get started", pages: ["docs/index", "docs/architecture", "docs/api-overview", "docs/quality", "docs/tooling"] }
  ];
  for (const spec of report.openapi) groups.push({ group: spec.title || "API reference", openapi: spec.path });
  return {
    $schema: "https://mintlify.com/docs.json",
    theme: "mint",
    name: `${titleCase(report.name)} Docs`,
    colors: { primary: "#2563EB", light: "#60A5FA", dark: "#1D4ED8" },
    navigation: { groups }
  };
}

function toolingTable(recommendations) {
  return [
    "| Tool | Fit | Why | Setup |",
    "| --- | --- | --- | --- |",
    ...recommendations.map((item) => `| [${item.tool}](${item.url}) | ${item.fit === "add-now" ? "Add now" : "Conditional"} | ${item.reason} | ${item.setup} |`)
  ].join("\n");
}

function workflow() {
  return `# Generated by infra-starter-pack. Safe to regenerate.
name: Mintlify docs

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  mintlify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 20
      - run: npx --yes mint@4.2.808 validate
`;
}

function securityWorkflow() {
  return `# Generated by infra-starter-pack. Safe to regenerate.
name: Secret scan

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Scan changed commits for secrets
        uses: trufflesecurity/trufflehog@6f3c981e7b77f235fd2702dd74af25fc4b72bf11 # v3.96.0
        with:
          extra_args: --results=verified,unknown
`;
}

export async function generateStarter(report, { root = report.root, force = false } = {}) {
  const name = titleCase(report.name);
  const languageLines = report.languages.map((item) => `${item.name} (${item.files} files)`);
  const frameworkLines = report.frameworks;
  const files = new Map([
    ["docs.json", `${JSON.stringify(docsConfig(report), null, 2)}\n`],
    ["docs/index.mdx", `---\ntitle: \"${name}\"\ndescription: \"Repository-aware documentation generated by infra-starter-pack\"\n---\n\n${GENERATED}\n\n# ${name}\n\n${report.description || "Welcome to the project documentation."}\n\n## What was detected\n\n${mdList(languageLines)}\n\n## Frameworks\n\n${mdList(frameworkLines)}\n\n<Info>This page is generated from repository evidence. Review product claims and examples before publishing.</Info>\n`],
    ["docs/architecture.mdx", `---\ntitle: \"Architecture\"\ndescription: \"A generated inventory of the repository\"\n---\n\n${GENERATED}\n\n# Architecture\n\n| Signal | Detected value |\n| --- | --- |\n| Package manager | ${report.packageManager || "Not detected"} |\n| Files scanned | ${report.totals.files} |\n| Source files | ${report.totals.sourceFiles} |\n| Frameworks | ${report.frameworks.join(", ") || "Not detected"} |\n| OpenAPI specs | ${report.openapi.length} |\n\n## Useful commands\n\n${Object.keys(report.scripts).length ? Object.keys(report.scripts).map((script) => `- \`${report.packageManager || "npm"} run ${script}\``).join("\n") : "- No package scripts detected"}\n`],
    ["docs/api-overview.mdx", `---\ntitle: \"API overview\"\ndescription: \"OpenAPI sources and heuristically detected routes\"\n---\n\n${GENERATED}\n\n# API overview\n\n## OpenAPI sources\n\n${report.openapi.length ? report.openapi.map((spec) => `- \`${spec.path}\` — ${spec.title}, OpenAPI ${spec.version}, ${spec.endpointCount} paths`).join("\n") : "No OpenAPI document was found. Add an OpenAPI 3.0 or 3.1 JSON/YAML file and regenerate to get Mintlify's interactive API reference."}\n\n## Detected routes\n\n${routeTable(report.routes)}\n\n<Warning>Route detection is a convenience inventory, not an API contract. OpenAPI is the authoritative input for generated API reference pages.</Warning>\n`],
    ["docs/quality.mdx", `---\ntitle: \"Runtime quality with Replay\"\ndescription: \"How this project uses Replay QA\"\n---\n\n${GENERATED}\n\n# Runtime quality with Replay QA\n\nReplay QA tests a running web application, not source code in isolation. It explores user journeys, writes and executes browser tests, records runtime behavior, and returns root-cause reports for bugs it finds.\n\n## Run a scan\n\n\`\`\`bash\nexport REPLAY_QA_TOKEN=\"lqa_...\"\nnpx infra-starter-pack replay \\\n  --target-url \"https://your-preview.example.com\" \\\n  --wait \\\n  --report infra-reports/replay-qa.json\n\`\`\`\n\nFor localhost, add \`--reverse-proxy\`, then follow the returned Replay proxy setup URL. Never commit the token or test credentials.\n\n## GitHub-native option\n\nInstall the Replay QA GitHub App from a Replay QA project to test pushes and pull requests without a workflow file. Publish source maps for file-and-line root cause reports.\n`],
    ["docs/tooling.mdx", `---\ntitle: "Recommended infrastructure tools"\ndescription: "Evidence-based additions from the a16z Infrastructure portfolio"\n---\n\n${GENERATED}\n\n# Recommended infrastructure tools\n\nThe starter applies one local, credential-free security control and recommends hosted products only when repository evidence justifies them. It never uploads source code or dependency metadata during generation.\n\n${toolingTable(report.toolingRecommendations)}\n\n<Info>TruffleHog is generated automatically. Socket, Braintrust, and Stainless require an explicit account or installation because they send selected data to an external service.</Info>\n`],
    [".infra-starter/scan-report", `${JSON.stringify({ ...report, root: "." }, null, 2)}\n`],
    [".github/workflows/infra-starter.yml", workflow()],
    [".github/workflows/infra-security.yml", securityWorkflow()]
  ]);

  const manifest = await readManifest(root);
  for (const [relative, contents] of files) {
    await assertSafeToWrite(root, relative, contents, force, manifest);
  }

  for (const [relative, contents] of files) {
    const file = path.join(root, relative);
    await fs.mkdir(path.dirname(file), { recursive: true });
    await fs.writeFile(file, contents, "utf8");
  }

  const nextManifest = {
    schemaVersion: 1,
    generator: "infra-starter-pack",
    generatedAt: new Date().toISOString(),
    files: Object.fromEntries([...files].map(([relative, contents]) => [relative, hash(contents)]))
  };
  const manifestFile = path.join(root, MANIFEST_PATH);
  await fs.mkdir(path.dirname(manifestFile), { recursive: true });
  await fs.writeFile(manifestFile, `${JSON.stringify(nextManifest, null, 2)}\n`, "utf8");
  return [...files.keys(), MANIFEST_PATH];
}
